<?php

/**
 * @file
 * Contains test_composer_json.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function test_composer_json_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the test_composer_json module.
    case 'help.page.test_composer_json':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function test_composer_json_theme() {
  return [
    'test_composer_json' => [
      'render element' => 'children',
    ],
  ];
}
