name: Sync to GitLab
on: [push]

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://git.drupalcode.org/project/testblah"
      env:
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "username"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "69354"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
